### ISSUE TITLE
[Análise] Acessibilidade

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-web#1]
# Resumo
Analisar a plataforma do plasmedis para adequação com as regras de acessibilidade do google e registrar os pontos de problema para cada página. Esses problemas podem ser registrados como comentários nessa issue mesmo.

# Critérios de Aceite

- [ ] /entrar
- [ ] /esqueci-minha-senha
- _Essas paginas abaixo precisa estar logado_
- [ ] /
- [ ] /form
- [ ] /complemento-de-dados
- [ ] /register
- [ ] /categorias
- [ ] /admin/controle-de-usuarios

# Protótipo

# Informações Adicionais
- [Testar acessibilidade usando o Lighthouse](https://learn.microsoft.com/pt-br/microsoft-edge/devtools-guide-chromium/accessibility/lighthouse)

**Comment by gacneves** [comment]
/entrar - Viewport computador

![/entrar](https://user-images.githubusercontent.com/57917229/227805172-61c8d6cc-f58e-47b9-ae90-c6f4ed944772.png)

Sem diferenças para o viewport mobile

**Comment by gacneves** [comment]
/esqueci-minha-senha - Viewport computador

![esqueci_minha_senha](https://user-images.githubusercontent.com/57917229/227805278-4ece5405-d5d3-4579-a54a-a8c5aed18290.png)

Sem diferenças para o viewport mobile

**Comment by gacneves** [comment]
/ - Viewport computador

![home](https://user-images.githubusercontent.com/57917229/227805342-339c1cf8-2989-4c00-86c2-74c30d3cca4e.png)

Problemas encontrados:
- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório
- Os botões de tipos de posts não tem valores arias válidos
- Baixo contraste em alguns textos na caixa do post

/ - Viewport mobile

![home_mobile](https://user-images.githubusercontent.com/57917229/229309551-d6591bb9-78e2-4dfd-b7b5-4de2aa65cc1f.png)

Problemas encontrados:
- Os botões da aba de cima não possuem valores válidos
- Os botões de tipos de posts não tem valores arias válidos
- Baixo contraste em alguns textos na caixa do post

**Comment by gacneves** [comment]
/perfil - Viewport computador

![perfil](https://user-images.githubusercontent.com/57917229/227809853-14ae83be-3773-421b-9150-394ec10b5e8e.png)

Problemas encontrados:
- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório
- O Campo data de nascimento não possui id
- O campo de "Possui Deficiência" possui vários rótulos
- Botão de "Salvar" com baixo contraste

/perfil - Viewport mobile

![perfil_mobile](https://user-images.githubusercontent.com/57917229/229308879-1bad384f-f8cd-4eb4-831d-028e1a4fb678.png)

Problemas encontrados:
- O botão de menu não tem um nome acessível
- O Campo data de nascimento não possui id
- O campo de "Possui Deficiência" possui vários rótulos
- Botão de "Salvar" com baixo contraste

**Comment by gacneves** [comment]
/register - Viewport computador

![register](https://user-images.githubusercontent.com/57917229/227810070-9bf52655-963a-49f6-9d5a-360bdb0d93de.png)

Problemas encontrados:
- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório
- Botão de "Cadastrar" com baixo contraste

/register - Viewport mobile

![register_mobile](https://user-images.githubusercontent.com/57917229/229308759-8f37c6c3-74d9-4d34-95d4-ca09ea63d522.png)

Problemas encontrados:
- O botão de menu não tem um nome acessível
- Botão de "Cadastrar" com baixo contraste

**Comment by gacneves** [comment]
/categorias - Viewport computador

![categorias](https://user-images.githubusercontent.com/57917229/227810247-45a9ca46-7b55-4493-ac46-6f9418dd793d.png)

Problema encontrado:

- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório

/categorias - Viewport mobile

![categorias_mobile](https://user-images.githubusercontent.com/57917229/229309402-e78c9ecc-f0f9-4892-bd02-789a4a1f69a1.png)

Problema encontrado:

- O botão de menu não tem um nome acessível

**Comment by gacneves** [comment]
/guia-de-uso - Viewport computador

![guia_de_uso](https://user-images.githubusercontent.com/57917229/227810318-05c6335b-2fa2-4fd5-951d-a5b88b2e0861.png)

Problema encontrado:

- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório

/guia-de-uso - Viewport mobile

![guia_de_uso_mobile](https://user-images.githubusercontent.com/57917229/229309664-429fca77-69c6-450c-8655-05771cab039e.png)

Problema encontrado:

- O botão de menu não tem um nome acessível

**Comment by gacneves** [comment]
/admin/controle-de-usuarios - Viewport computador

![controle_de_usuarios](https://user-images.githubusercontent.com/57917229/227810379-486bd14e-9bbf-41f7-ab41-188be95e7a8e.png)

Problemas encontrados:

- Os botões da barra de menu da esquerda não possuem um elemento pai obrigatório
- Os botões de edição de usuário não tem um nome acessível
- O botão "Pesquisar" não tem uma taxa de contraste suficiente

/admin/controle-de-usuarios - Viewport mobile

![controle_de_usuarios_mobile](https://user-images.githubusercontent.com/57917229/229309838-f7de1efc-f5fe-414d-8509-c026e0f924be.png)

Problemas encontrados:
- O botão de menu não tem um nome acessível
- O botão "Pesquisar" não tem uma taxa de contraste suficiente

**Comment by dsalexan** [comment]
@gacneves a pontuação é igual se estiver num viewport mobile?

**Comment by gacneves** [comment]
> @gacneves a pontuação é igual se estiver num viewport mobile?

@dsalexan  Tem algumas diferenças, vou atualizar os comentários acima
