### ISSUE TITLE
[Paginação] Adaptar UI

### ISSUE THREAD

**Issue by dsalexan** [UnifespCodeLab/plasmedis-web#14]
# História de Usuário

# Resumo

Adaptar o recebimento das chamadas da api para lidar com um resultado paginado.

Vai envolver corrigir os campos recebidos e criar novas interações para poder "trocar a página". Essas novas interações podem ser um scroll event (no caso do feed) ou um botão de proxima página (no caso de tabelas, por exemplo).

Checar a planilha [Geral](https://docs.google.com/spreadsheets/d/1hgf2RedFsMHG74lhUaUBPXuN9ApAKwHe/edit#gid=1864772177), na aba **API** para verificar quais endpoints são paginados e a aba **UI** para verificar quais telas chamam determinados endpoints.

# Critérios de Aceite

- [x] Adaptar as telas para aceitar paginação
  - [x] /categorias
  - [x] /admin/controle-de-usuarios
  - [x] / (feed)
    - [x] Comentários de uma postagem

# Protótipo

# Informações Adicionais

- Paginação ([plasmedis-api #10](https://github.com/UnifespCodeLab/plasmedis-api/issues/10))
    - Implementação de paginação na api

**Comment by gacneves** [comment]
Paginação das tabelas (controle de categorias e usuários)

[Screencast from 28-05-2023 13:09:46.webm](https://github.com/UnifespCodeLab/plasmedis-web/assets/57917229/3e506210-c9f0-418d-84c9-55a8ce46333c)

[Screencast from 28-05-2023 13:10:46.webm](https://github.com/UnifespCodeLab/plasmedis-web/assets/57917229/5245dbe6-329b-4d53-ba18-f1af79c197ec)

**Comment by gacneves** [comment]
Paginação dos comentários

[Comentarios](https://github.com/UnifespCodeLab/plasmedis-web/assets/57917229/e3aa6dba-1864-4146-bae6-fe85d5fb09fe)

**Comment by gacneves** [comment]
Paginação do Feed (Scroll infinito)

[Screencast from 05-06-2023 23:00:42.webm](https://github.com/UnifespCodeLab/plasmedis-web/assets/57917229/9075cd08-25d2-4717-8de7-8dc0b2c28530)
